name: Deploy

on:
  push:
    branches: ['main']
  workflow_dispatch:

jobs:
  runtime:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8.6.1
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: pnpm
      - name: 'install'
        run: pnpm -r i --frozen-lockfile
      - name: 'build'
        run: pnpm build
      - uses: actions/upload-pages-artifact@v1
        with:
          path: dist
      - uses: actions/deploy-pages@v1
        id: deployment
      - name: 'logging'
        run: echo "Deployed at ${{ steps.deployment.outputs.page_url }}"
